---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
          - name: tmp
            mountPath: /tmp
          - name: nginx-cache
            mountPath: /var/cache/nginx
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            items:
              - key: {{ .Values.nginxConf }}
                path: {{ .Values.nginxConf }}
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
