CREATE TABLE IF NOT EXISTS product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    price       DOUBLE PRECISION,
    picture_url VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_created DATE,
    status       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS order_product (
    order_id   BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    PRIMARY KEY (order_id, product_id)
);
