---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  postgres_uri: {{ .Values.env.postgresUri }}
  report_path: {{ .Values.env.reportPath }}
  log_path: {{ .Values.env.logPath }}
  vault_host: {{ .Values.vault.host | quote }}
  vault_port: {{ .Values.vault.port | quote }}
  vault_scheme: {{ .Values.vault.scheme | quote }}
  vault_kv_version: {{ .Values.vault.kvVersion | quote }}
